import { useSharedValue } from "react-native-reanimated";
import { getRandomColor } from "../helpers/color";
import { AppType } from "../types/AppType";

const useApps = () => {
  const apps = useSharedValue<AppType[]>([
    {
      id: "com.app.mail",
      screen: 0,
      x: useSharedValue(0),
      y: useSharedValue(0),
      labelOpacity: useSharedValue(1),
      name: "Mail",
      backgroundColor: useSharedValue(getRandomColor()),
      isMoving: useSharedValue(false),
    },
    {
      id: "com.app.notes",
      screen: 0,
      x: useSharedValue(0),
      y: useSharedValue(0),
      labelOpacity: useSharedValue(1),
      name: "Notes",
      backgroundColor: useSharedValue(getRandomColor()),
      isMoving: useSharedValue(false),
    },
    {
      id: "com.app.camera",
      screen: 0,
      x: useSharedValue(0),
      y: useSharedValue(0),
      labelOpacity: useSharedValue(1),
      name: "Camera",
      backgroundColor: useSharedValue(getRandomColor()),
      isMoving: useSharedValue(false),
    },
    {
      id: "com.app.settings",
      screen: 0,
      x: useSharedValue(0),
      y: useSharedValue(0),
      labelOpacity: useSharedValue(1),
      name: "Settings",
      backgroundColor: useSharedValue(getRandomColor()),
      isMoving: useSharedValue(false),
    },
    {
      id: "com.app.maps",
      screen: 0,
      x: useSharedValue(0),
      y: useSharedValue(0),
      labelOpacity: useSharedValue(1),
      name: "Maps",
      backgroundColor: useSharedValue(getRandomColor()),
      isMoving: useSharedValue(false),
    },
    {
      id: "com.app.appstore",
      screen: 0,
      x: useSharedValue(0),
      y: useSharedValue(0),
      labelOpacity: useSharedValue(1),
      name: "App Store",
      backgroundColor: useSharedValue(getRandomColor()),
      isMoving: useSharedValue(false),
    },
    {
      id: "com.app.appstore2",
      screen: 0,
      x: useSharedValue(0),
      y: useSharedValue(0),
      labelOpacity: useSharedValue(1),
      name: "App Store 2",
      backgroundColor: useSharedValue(getRandomColor()),
      isMoving: useSharedValue(false),
    },
    {
      id: "com.app.appstore3",
      screen: 0,
      x: useSharedValue(0),
      y: useSharedValue(0),
      labelOpacity: useSharedValue(1),
      name: "App Store 3",
      backgroundColor: useSharedValue(getRandomColor()),
      isMoving: useSharedValue(false),
    },
    {
      id: "com.app.appstore4",
      screen: 1,
      x: useSharedValue(0),
      y: useSharedValue(0),
      labelOpacity: useSharedValue(1),
      name: "App Store 4",
      backgroundColor: useSharedValue(getRandomColor()),
      isMoving: useSharedValue(false),
    },
    {
      id: "com.app.appstore5",
      screen: 1,
      x: useSharedValue(0),
      y: useSharedValue(0),
      labelOpacity: useSharedValue(1),
      name: "App Store 5",
      backgroundColor: useSharedValue(getRandomColor()),
      isMoving: useSharedValue(false),
    },
    {
      id: "com.app.appstore6",
      screen: 1,
      x: useSharedValue(0),
      y: useSharedValue(0),
      labelOpacity: useSharedValue(1),
      name: "App Store 6",
      backgroundColor: useSharedValue(getRandomColor()),
      isMoving: useSharedValue(false),
    },
    {
      id: "com.app.appstore7",
      screen: 1,
      x: useSharedValue(0),
      y: useSharedValue(0),
      labelOpacity: useSharedValue(1),
      name: "App Store 7",
      backgroundColor: useSharedValue(getRandomColor()),
      isMoving: useSharedValue(false),
    },
    {
      id: "com.app.appstore8",
      screen: 1,
      x: useSharedValue(0),
      y: useSharedValue(0),
      labelOpacity: useSharedValue(1),
      name: "App Store 8",
      backgroundColor: useSharedValue(getRandomColor()),
      isMoving: useSharedValue(false),
    },
  ]);
  return { apps };
};

export default useApps;
